GET https://reumgbrqwd.execute-api.us-east-1.amazonaws.com/dev/appointments/user/2021-02-25
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjB1R1l2Wjc2c2ZUQ0c2LWRRYjhyWCJ9.eyJpc3MiOiJodHRwczovL215dGVjaDYudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwMDgwMGZiZTE4NzcwMDA2OWI1ZmM1YiIsImF1ZCI6WyJodHRwczovL2NhcHN0b25lLnVkYWNpdHkiLCJodHRwczovL215dGVjaDYudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxMzY0MDI4NiwiZXhwIjoxNjEzNzI2Njg2LCJhenAiOiJSQ2xuOXFjdmFpVmRndFptM2xPQ3NjeWFyRlc5azRTOSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6WyJjcmVhdGU6dXNlci1hcHBvaW50bWVudHMiLCJkZWxldGU6dXNlci1hcHBvaW50bWVudHMiLCJyZWFkOnVzZXItYXBwb2ludG1lbnRzIl19.hY1mXqtokG5iUXtanI9YUtpKww_dEmZQQE2WRaoVrIQC3Bi1ZTZmbU4UYkn804b9zOxQ1XPvaeo7o0PzcuFfeLPyIAFjyYHEIL11H8aweKJV5QzId6gzcLw3fU8gNUKILSxVOByf1BCqpZbqL8KiF4NjPqjca0XHdTGgpgaljyi-MZGwAor5jyYxLBZ9zj8MckTYicorlhhgCs6zeJ3IbS0_c3SOrSubXocUWhMYUcg5QepiziZwllaYNrmb3y8ooLUr9xnEDZel35LJUUtgr7nmDP37ghH4jJo1-60IPM8YDKMRgow46NyfLFX8RPOwJ_52dNPgR3ATJ6ZI6GUeoQ
